In [2]:
conda install NumPy

Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

the Basics

In [17]:
# at the end of this array i have specified a smaller data type
# by default it is int64 but int16 will be smaller and thus faster
# # but will be unable to handle quite as large numbers 
# because they memory usage will be smaller
a = np.array([1,2,3],dtype='int16')
print(a)

[1 2 3]


In [8]:
# NOTE: array require both parentheses and brackets
# when doing more than one nested group
# a second set of brackets is required around that group.
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [9]:
# get deminsion of numpy array
a.ndim

1

In [12]:
# getshape of array
b.shape


(2, 3)

In [18]:
# get type
a.dtype

dtype('int16')

In [19]:
# get size
# because i specified int16 above this went from a size of 8 to a size of 2
a.itemsize

2

In [20]:
# total size
a.size

3

In [22]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
# get a specific element
a[1,5]

13

In [24]:
# get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [25]:
# get a specific column
a[:,2]

array([ 3, 10])

In [27]:
# get different step size
# 2 is the step size note the colon
a[0,1:6:2]

array([2, 4, 6])

In [28]:
# change elements
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [29]:
# replace a column
a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [33]:
# how to initialize an all 0s array
np.zeros((2))
np.zeros((2,3))
np.zeros((2,3,4))
np.zeros((2,3,4,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [34]:
# all 1s matrix
# same as above it can be as many diminsions as you want
np.ones((3))

array([1., 1., 1.])

In [39]:
# any other number
a = np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [38]:
print(a)

[[99. 99.]
 [99. 99.]]


In [40]:
# any other number full_like
# makes an array the same shape as a previously 
# created array but with whatever number you choose
np.full_like(a,4)

array([[4., 4.],
       [4., 4.]], dtype=float32)

In [43]:
# matrix of random number to start
np.random.rand(4,2,3)

array([[[0.14416344, 0.48058578, 0.09555103],
        [0.19418915, 0.4044525 , 0.40892469]],

       [[0.69665375, 0.43196592, 0.34452941],
        [0.4055825 , 0.94459948, 0.3826677 ]],

       [[0.00643794, 0.87491378, 0.22981846],
        [0.51493833, 0.84738226, 0.55876363]],

       [[0.08629701, 0.8914626 , 0.51924212],
        [0.01850314, 0.90176483, 0.49829228]]])

In [47]:
# random int values
np.random.randint(4,7,size=(3,3))

array([[5, 5, 6],
       [5, 6, 5],
       [4, 5, 4]])

In [50]:
# only needs one parameter because by nature 
# identity is a square matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [57]:
# putting a second set of brackets makes it a 2d array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [65]:
output = np.ones([5,5])
output[1:4,1:4]=0
output[2,2]=9
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [68]:
# he did it this way
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1]=9
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [69]:
# interesting how he created a second matrix and layed it inside
output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [72]:
# if you want to make a copy of an array you have to use a .copy()
# otherwise the copy simply points to the same thing and 
# changing either copy will change the original
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


In [73]:
a = np.array([1,2,3,4])

In [74]:
a+2

array([3, 4, 5, 6])

In [75]:
a-2

array([-1,  0,  1,  2])

In [76]:
a*2

array([2, 4, 6, 8])

In [77]:
a**2

array([ 1,  4,  9, 16])

In [78]:
b = np.array([1,0,1,0])

In [79]:
a+b

array([2, 2, 4, 4])

In [81]:
# it is interesting to note that these math functions do not change the underlying array
print(a)

[1 2 3 4]


In [82]:
# take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [83]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

Linear Algebra

In [96]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)


np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [98]:
c = np.identity(3)
np.linalg.det(c)

1.0

statistics

In [99]:
stats = np.array([[1,2,3],[4,5,6]])

In [103]:
np.min(stats,axis=1)

array([1, 4])

In [101]:
np.max(stats)

6

In [104]:
np.sum(stats)

21

In [107]:
before = np.array([[1,2,3,4],[5,6,7,8]])

In [108]:
before.shape

(2, 4)

In [111]:
after = before.reshape(4,2)

In [112]:
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [114]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [120]:
# this won't run because the file was never created but 
# also there doesn't seem to be a good way to encode
np.genfromtxt('test.pdf',delimiter='int32')
filedata.astype('int64')